### ISSUE TITLE
Task list for migrating to new planning API

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#413]
**General**
- [ ] (JS) Revive old snap planner function
- [ ] (JS) Write tests for the new API framework (w/o tests for concrete planners)

**Planners**
  * OMPL
    - [ ] (ooo) planOMPL (config-to-config)
    - [ ] (ooo) planOMPL (config-to-region)
    - [ ] (ooo) planCRRT
    - [ ] (ooo) planCRRTConnect
  * Vector field
    - [ ] (ooo) planToEndEffectorOffset
    - [ ] (ooo) planToEndEffectorPose
  * Composite
    - [ ] (ooo) FirstSupportedMetaPlanner
    - [ ] (ooo) RankedMetaPlanner
    - [ ] (ooo) SequenceMetaPlanner

**Common to all tasks**
* Please write tests for new planners
* Keep the current planning functions not to break the downstream projects _yet_
* Mark the current planning functions as deprecated
